# yaml-language-server: $schema=../state-machine-schema.json
---
name: "minor"
description: "A streamlined workflow for small-impact changes: Explore (analysis + design) → Implement (code + test + commit) - optimized for minor enhancements"
initial_state: "explore"

# States with default instructions and transitions
states:
  explore:
    description: "Analysis and design phase - understanding and planning without implementation"
    default_instructions: >
                          Starting exploration phase for minor enhancement. 
                          This phase should be efficient since it's a minor enhancement.
                          Understand the problem, analyze existing patterns, and design your approach. 
                          Consider the scope and impact of the change. Document your analysis and design decisions in the plan file. 
                          Focus on analysis and design only - do not write any code yet.
    transitions:
      - trigger: "exploration_complete"
        to: "implement"
        instructions: >
          Analysis and design complete! ✅ Now transition to implementation phase.
          You have a clear understanding of the problem and a solid design approach.
          Now implement the solution by writing code, testing it, and preparing for commit.
          Follow your design decisions and keep the scope focused on the minor enhancement.
          Update the plan file with implementation progress and mark completed exploration tasks.
        transition_reason: "Analysis and design complete, ready for streamlined implementation"
      
      - trigger: "abandon_feature"
        to: "explore"
        instructions: >
          Minor enhancement abandoned. Revert potentially made changes. 
          Return to exploration state for new tasks.
          The plan file will remain for future reference if needed.
        additional_instructions: "Minor enhancement development abandoned. Clean up any analysis work and prepare for new tasks."
        transition_reason: "User decided to abandon current minor enhancement"

  implement:
    description: "Combined implementation phase - code, test, and commit"
    default_instructions: "Starting implementation phase for minor enhancement. This phase combines coding, testing, and commit preparation. Follow your design from the exploration phase. Write clean, focused code for the minor enhancement. Test your changes to ensure they work correctly and don't break existing functionality. Prepare documentation and commit when ready. Update progress in the plan file."
    transitions:
      - trigger: "need_more_analysis"
        to: "explore"
        additional_instructions: "Implementation revealed gaps in analysis or design. Focus on the specific areas that need clarification before continuing with implementation."
        transition_reason: "Implementation work revealed need for more analysis or design"
      
      - trigger: "implementation_complete"
        to: "explore"
        instructions: >
          Minor enhancement is complete! ✅ All implementation, testing, and commit work is finished.
          The feature is ready for delivery. Return to exploration state, ready for the next minor enhancement or task.
          Mark all implementation tasks as complete in the plan file.
        additional_instructions: "Minor enhancement is complete and ready for delivery. Prepare for the next development task."
        transition_reason: "Minor enhancement delivery complete, ready for next task"
      
      - trigger: "abandon_feature"
        to: "explore"
        instructions: >
          Minor enhancement abandoned during implementation. Clean up any incomplete code and return to exploration.
          The plan file and any completed work will remain for future reference.
        additional_instructions: "Minor enhancement abandoned during implementation. Clean up any incomplete code and prepare for new tasks."
        transition_reason: "User decided to abandon minor enhancement during implementation"
